language: python
python:
    - "3.7"
install: pip install -r requarements.txt
script:
    - python -m pytest --pep8 && python -m pytest -v --cov=.
after_success:
  - bash <(curl -s https://codecov.io/bash)