stages:
  extract_sensors:
    cmd: python -m src.data.spatial_data
    deps:
      - DATA/raw/weather
      - DATA/raw/sensors
      - src/data/utils.py
      - src/data/opentopodata.py
      - src/data/osmdata.py
      - requirements.txt
    outs:
      - DATA/processed/sensors.csv
  create_dataset:
    cmd: python -m src.data.sensors_data
    deps:
      - DATA/raw/weather
      - DATA/raw/sensors
      - src/data/utils.py
      - src/data/sensors_data.py
      - DATA/processed/sensors.csv
    outs:
      - DATA/processed/dataset.csv

